-- Generated by Matugen - do not edit manually
local M = {}

M.colors = {
  bg = "{{colors.surface.default.hex}}",
  bg_dark = "{{colors.surface_container.default.hex}}",
  fg = "{{colors.on_surface.default.hex}}",
  primary = "{{colors.primary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  accent = "{{colors.tertiary.default.hex}}",
  error = "{{colors.error.default.hex}}",
  warning = "{{colors.secondary.default.hex}}",
  info = "{{colors.primary.default.hex}}",
  hint = "{{colors.surface_variant.default.hex}}",
}

return M
