monitor = , preferred, auto, 1

input {
    kb_layout = us
    follow_mouse = 1
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    layout = dwindle
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

bind = SUPER, Return, exec, ghostty
bind = SUPER SHIFT, Return, exec, ghostty --class=ghostty-float
bind = SUPER, E, exec, nautilus
bind = SUPER SHIFT, Q, exit

