#!/usr/bin/env bash
# lib/runtime.sh — Runtime environment files for session scripts and systemd.
set -euo pipefail

runtime::quote_shell() {
  printf '%q' "$1"
}

runtime::write_env() {
  local root="${1:?dotfiles root required}"
  local config_dir="${HOME}/.config/lumina"
  local shell_env="${config_dir}/env.sh"
  local systemd_env_dir="${HOME}/.config/environment.d"
  local systemd_env="${systemd_env_dir}/10-lumina.conf"

  mkdir -p "${config_dir}" "${systemd_env_dir}"

  {
    printf '# Generated by lumina-dots. Re-run install.sh dotfiles-only after moving the repo.\n'
    printf 'export DOTFILES_DIR=%s\n' "$(runtime::quote_shell "${root}")"
    printf 'export LOQDOTS_ROOT=%s\n' "$(runtime::quote_shell "${root}")"
  } >"${shell_env}"

  {
    printf '# Generated by lumina-dots. Re-run install.sh dotfiles-only after moving the repo.\n'
    printf 'DOTFILES_DIR=%s\n' "${root}"
    printf 'LOQDOTS_ROOT=%s\n' "${root}"
  } >"${systemd_env}"

  chmod 0644 "${shell_env}" "${systemd_env}"
}

runtime::load_env() {
  local shell_env="${HOME}/.config/lumina/env.sh"

  if [[ -f "${shell_env}" ]]; then
    # shellcheck disable=SC1090
    source "${shell_env}"
  fi
}
