#!/usr/bin/env bash
set -euo pipefail

CUSTOM_MONITORS="${HOME}/.config/hypr/custom/monitors.conf"
mkdir -p "$(dirname "${CUSTOM_MONITORS}")"

if ! command -v hyprctl >/dev/null 2>&1; then
  exit 0
fi

MONITOR_COUNT="$(
  hyprctl monitors -j 2>/dev/null |
    python3 -c 'import json,sys; print(len(json.load(sys.stdin)))' 2>/dev/null ||
    printf '1\n'
)"

if [[ "${MONITOR_COUNT}" -le 1 ]]; then
  rm -f "${CUSTOM_MONITORS}"
else
  cat >"${CUSTOM_MONITORS}" <<'EOF'
# Auto-generated by monitor-detect.sh
monitor = eDP-1, 1920x1080@144, 2560x0, 1
monitor = , preferred, 0x0, 1

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:, default:true
workspace = 7, monitor:, default:true
workspace = 8, monitor:, default:true
workspace = 9, monitor:, default:true
workspace = 10, monitor:, default:true
EOF
fi

hyprctl reload >/dev/null 2>&1 || true
