color_theme = "loq.theme"
theme_background = False
vim_keys = True
rounded_corners = True
update_ms = 1200
proc_sorting = "cpu lazy"
proc_tree = False
cpu_sensor = "Auto"
show_gpu_info = False
clock_format = "%H:%M"
background_update = True
net_sync = True

