"""Glass Engine: the sole authority for Lumina surface effects."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from dataclasses import asdict, dataclass, replace
from enum import Enum
from pathlib import Path
from typing import Iterable

from .ipc import emit_settings_changed
from .schema import validate_config
from .theme import FALLBACK_TOKENS


class GlassMode(str, Enum):
    CRYSTAL = "crystal"
    FROSTED = "frosted"
    MICA = "mica"
    MATERIAL = "material"
    MINIMAL = "minimal"


@dataclass(frozen=True)
class GlassConfig:
    mode: GlassMode
    blur_size: int
    blur_passes: int
    opacity: float
    saturation: float
    tint_color: str
    noise: float
    brightness: float
    performance_mode: bool = False
    battery_mode: bool = False


def _preset(mode: GlassMode, blur: int, passes: int, opacity: float, saturation: float, noise: float, brightness: float) -> GlassConfig:
    return GlassConfig(mode, blur, passes, opacity, saturation, str(FALLBACK_TOKENS["colors"]["primary"]), noise, brightness)


GLASS_PRESETS = {
    GlassMode.CRYSTAL: _preset(GlassMode.CRYSTAL, 28, 4, .55, 1.4, .025, .95),
    GlassMode.FROSTED: _preset(GlassMode.FROSTED, 20, 3, .72, 1.2, .018, .90),
    GlassMode.MICA: _preset(GlassMode.MICA, 12, 2, .85, 1.0, .012, .88),
    GlassMode.MATERIAL: _preset(GlassMode.MATERIAL, 6, 1, .92, .9, .006, 1.0),
    GlassMode.MINIMAL: _preset(GlassMode.MINIMAL, 0, 0, 1.0, 1.0, 0.0, 1.0),
}


def glass_config_path() -> Path:
    return Path(os.environ.get("LUMINA_CONFIG_HOME", Path.home() / ".config/lumina")) / "glass.json"


def on_battery() -> bool:
    override = os.environ.get("LUMINA_ON_BATTERY")
    if override is not None: return override.lower() in {"1", "true", "yes"}
    supplies = Path("/sys/class/power_supply")
    try:
        return any((item / "status").read_text().strip() == "Discharging" for item in supplies.glob("BAT*") if (item / "status").exists())
    except OSError: return False


def _effective(cfg: GlassConfig) -> GlassConfig:
    if cfg.battery_mode or on_battery():
        return replace(GLASS_PRESETS[GlassMode.MINIMAL], battery_mode=True)
    if cfg.performance_mode:
        return replace(cfg, blur_size=cfg.blur_size // 2, blur_passes=cfg.blur_passes // 2)
    return cfg


def load_glass_config() -> GlassConfig:
    try:
        data = json.loads(glass_config_path().read_text(encoding="utf-8"))
        mode = GlassMode(data.get("mode", GlassMode.FROSTED.value))
        base = asdict(GLASS_PRESETS[mode])
        base.update(data)
        base["mode"] = mode
        return GlassConfig(**base)
    except (FileNotFoundError, OSError, ValueError, TypeError, json.JSONDecodeError):
        return GLASS_PRESETS[GlassMode.FROSTED]


def save_glass_config(cfg: GlassConfig) -> None:
    path = glass_config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = asdict(cfg)
    payload["mode"] = cfg.mode.value
    validate_config("glass", payload)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    emit_settings_changed("glass", cfg.mode.value)


def glass_css(cfg: GlassConfig) -> str:
    active = _effective(cfg)
    surface_weight = max(0.0, min(100.0, active.opacity * 100.0))
    return "\n".join((
        ":root {",
        f"  --glass-bg: color-mix(in srgb, var(--lumina-colors-surface) {surface_weight:.1f}%, transparent);",
        f"  --glass-blur: {active.blur_size}px;",
        f"  --glass-noise: {active.noise:.3f};",
        "  --glass-border: color-mix(in srgb, var(--lumina-colors-on-surface) 12%, transparent);",
        f"  --glass-tint: {active.tint_color};",
        f"  --glass-bright: {active.brightness:.3f};",
        "}", "",
    ))


def glass_classes() -> list[str]:
    return ["lumina-control-center", "lumina-keybind-overlay", "lumina-settings-studio", "lumina-mission-control", "walker"]


def apply_glass_layerrules(cfg: GlassConfig, classes: Iterable[str] | None = None) -> Path:
    active = _effective(cfg)
    blur_enabled = active.mode is not GlassMode.MINIMAL and active.blur_size > 0 and active.blur_passes > 0
    path = Path(os.environ.get("LUMINA_HYPR_CONFIG", Path.home() / ".config/hypr")) / "conf.d/glass-rules.conf"
    path.parent.mkdir(parents=True, exist_ok=True)
    enabled = "true" if blur_enabled else "false"
    rules: list[str] = [
        "# Generated by lumina-glass. Do not edit.",
        "decoration {",
        "  blur {",
        f"    enabled = {enabled}",
        f"    size = {active.blur_size}",
        f"    passes = {active.blur_passes}",
        f"    noise = {active.noise:.3f}",
        f"    brightness = {active.brightness:.3f}",
        f"    vibrancy = {active.saturation:.3f}",
        "  }",
        "}",
    ]
    commands: list[str] = [
        f"keyword decoration:blur:enabled {enabled}",
        f"keyword decoration:blur:size {active.blur_size}",
        f"keyword decoration:blur:passes {active.blur_passes}",
        f"keyword decoration:blur:noise {active.noise:.3f}",
        f"keyword decoration:blur:brightness {active.brightness:.3f}",
        f"keyword decoration:blur:vibrancy {active.saturation:.3f}",
    ]
    for class_name in classes or glass_classes():
        match = f"match:class ^({class_name})$"
        blur_rule = f"blur {'on' if blur_enabled else 'off'}, {match}"
        opacity_rule = f"opacity {active.opacity:.3f} override, {match}"
        rules.extend((f"layerrule = {blur_rule}", f"layerrule = {opacity_rule}"))
        commands.extend((f"keyword layerrule '{blur_rule}'", f"keyword layerrule '{opacity_rule}'"))
    tmp = path.with_suffix(".conf.tmp")
    tmp.write_text("\n".join(rules) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    if os.environ.get("HYPRLAND_INSTANCE_SIGNATURE") and shutil.which("hyprctl"):
        subprocess.Popen(["hyprctl", "--batch", "; ".join(commands)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return path


def set_glass_mode(mode: GlassMode | str, *, battery_override: bool | None = None) -> GlassConfig:
    """Apply a preset through the canonical Glass API and persist only normal mode changes."""
    selected = GlassMode(mode)
    battery = on_battery() if battery_override is None else battery_override
    cfg = GLASS_PRESETS[selected]
    if battery:
        cfg = replace(cfg, battery_mode=True)
    else:
        save_glass_config(cfg)
    apply_glass_layerrules(cfg)
    return _effective(cfg)
